const $=x=>document.getElementById(x);let age=0,si=0;
const S=[["Human","The whole person is the starting point.","~1 m",1],["Organ","A coordinated body structure made of tissues.","~0.1 m",.82],["Tissue","Many specialized cells working together.","~1–10 cm",.64],["Cell","A living unit with membranes and internal machinery.","~10 µm",.46],["Nucleus","A compartment containing chromosomes.","~5 µm",.30],["DNA","Molecular information encoded in microscopic structures.","~2 nm wide",.17]];
const C=[["🩸","Red blood cell","~120 days","Carries oxygen and carbon dioxide; mature cells circulate without a nucleus."],["🧴","Skin cell","weeks to months","Outer skin is continually renewed as cells move toward the surface."],["🦠","Intestinal lining cell","often days","Many lining cells are replaced quickly because the tissue experiences constant wear."],["🧠","Neuron","often decades","Many neurons are long-lived and can persist for much of a person's life."],["🫀","Heart muscle cell","long-lived","Heart muscle cells generally turn over much more slowly than rapidly renewing tissues."],["🦴","Bone cell","varies","Bone is living tissue continually remodeled by different cell types."],["🛡️","Immune cell","days to years","Different immune populations have very different lifespans and roles."],["🧪","Liver cell","months to years","Liver tissue has substantial maintenance and repair capacity; turnover varies by cell type."]];
const F=[["Some cells may outlive others by decades.","Cell turnover is not one universal body-wide clock."],["A chromosome is a DNA-packing structure.","Packaging helps very long DNA molecules fit inside the nucleus."],["Your body is a community of specialized cells.","Different shapes and molecular machinery enable different jobs."],["Bone is living tissue.","Bone is continually broken down and rebuilt through remodeling."],["One number cannot perfectly describe cellular age.","Different tissues have dramatically different renewal rates."]];
function fmt(n){return Math.round(n).toLocaleString()}
function calc(){let days=age*365.2425,d=+$("d").value,h=+$("h").value,b=+$("br").value;$("time").textContent=fmt(days)+" days";$("breakdown").textContent=`≈ ${fmt(days*24)} hours · ${fmt(days*86400)} seconds`;$("gens").textContent=fmt(days/d);$("beats").textContent=fmt(days*1440*h);$("breaths").textContent=fmt(days*1440*b);$("seconds").textContent=fmt(days*86400);$("lbeat").textContent=fmt(days*1440*h);$("lbreath").textContent=fmt(days*1440*b);$("ldays").textContent=fmt(days);$("labgen").textContent=fmt(days/d);$("meter").style.width=Math.min(100,age)+"%";document.querySelectorAll(".bars i")[0].style.height=Math.min(100,h-40)+"%";document.querySelectorAll(".bars i")[1].style.height=Math.min(100,b*3)+"%";document.querySelectorAll(".bars i")[2].style.height=Math.min(100,127-d)+"%"}
function cells(){ $("cellsGrid").innerHTML=C.map((c,i)=>`<button class="cell-card" data-i="${i}"><div class="ico">${c[0]}</div><h3>${c[1]}</h3><small>${c[2]}</small><p>${c[3].slice(0,72)}…</p></button>`).join("");document.querySelectorAll(".cell-card").forEach(x=>x.onclick=()=>cell(+x.dataset.i));cell(0)}
function cell(i){let c=C[i];document.querySelectorAll(".cell-card").forEach((x,n)=>x.classList.toggle("active",n===i));$("cellInfo").innerHTML=`<small>${c[1]}</small><h3>${c[0]} ${c[1]}</h3><p>${c[3]}</p><span class="tag">${c[2]}</span>`}
function scale(){let s=S[si];$("step").textContent=`${si+1} / ${S.length}`;$("scaleTitle").textContent=s[0];$("scaleText").textContent=s[1];$("scaleSize").textContent=s[2];$("scaleOrb").textContent=s[0].toUpperCase();$("scaleOrb").style.transform=`scale(${s[3]})`;document.querySelectorAll(".dot").forEach((x,i)=>x.classList.toggle("on",i===si))}
$("go").onclick=()=>{let v=+$("age").value;if(v<1||v>120){$("err").textContent="Enter an age from 1 to 120.";return}age=v;$("err").textContent="";$("dashboard").classList.remove("hidden");calc();timeline();$("dashboard").scrollIntoView({behavior:"smooth"})};$("age").onkeydown=e=>{if(e.key==="Enter")$("go").click()};$("change").onclick=()=>$("age").focus();
$("dots").innerHTML=S.map((_,i)=>`<i class="dot" data-i="${i}"></i>`).join("");$("prev").onclick=()=>{si=(si+5)%6;scale()};$("next").onclick=()=>{si=(si+1)%6;scale()};document.querySelectorAll(".dot").forEach(x=>x.onclick=()=>{si=+x.dataset.i;scale()});
$("dnaBtn").onclick=()=>{let p=$("dnaVisual").classList.toggle("packed");$("dnaStage").textContent=p?"PACKED DNA":"DNA";$("dnaSize").textContent=p?"microscopic packaging":"~2 m";$("dnaText").textContent=p?"A simplified animation of DNA becoming increasingly compact.":"Approximate stretched-out DNA length in one diploid cell.";$("dnaBtn").textContent=p?"Unpack the DNA ←":"Pack the DNA →"};
["d","h","br"].forEach(id=>$(id).oninput=()=>{let v=$(id).value;if(id==="d")$("dv").textContent=v+" days";if(id==="h")$("hv").textContent=v+" bpm";if(id==="br")$("bv").textContent=v+" / min";if(age)calc()});
function timeline(){let p=[["BIRTH",0,"Your starting point."],["EARLY DEVELOPMENT",Math.min(2,age),"Rapid growth and development."],["MIDPOINT",Math.max(1,Math.round(age/2)),"A midpoint marker."],["TODAY",age,"Your current point."]];$("timeline").innerHTML=p.filter((x,i,a)=>i===0||x[1]!==a[i-1][1]).map(x=>`<article class="event"><small>AGE ${x[1]}</small><h3>${x[0]}</h3><p>${x[2]}</p></article>`).join("")}
$("summaryBtn").onclick=()=>{$("summary").classList.remove("hidden");$("summary").innerHTML=age?`At age <b>${age}</b>, this model gives about <b>${fmt(age*365.2425/+$("d").value)}</b> cell-generation intervals, <b>${fmt(age*365.2425*1440*+$("h").value)}</b> heartbeats and <b>${fmt(age*365.2425*1440*+$("br").value)}</b> breaths.`:"Enter your age first, then reveal the summary."};
$("factBtn").onclick=()=>{let f=F[Math.floor(Math.random()*F.length)];$("fact").textContent=f[0];$("why").textContent=f[1]};
for(let i=0;i<80;i++){let x=document.createElement("i");x.className="star";x.style.left=Math.random()*100+"%";x.style.top=Math.random()*100+"%";x.style.animationDelay=Math.random()*4+"s";$("stars").appendChild(x)}
setInterval(()=>{if(age){let h=+$("h").value,t=Math.floor(Date.now()/1000);$("clock").textContent=fmt(Math.floor(t*h/60)%Math.max(h,1)+1)}},1000);cells();scale();