name = "nivinpadaveettil-manavalan-ai"
main = "./.output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./.output/public", binding = "ASSETS" }

[build]
command = "npm run build"
