import {test, expect} from '@playwright/test';
const play=async page=>{await page.getByRole('button',{name:/Play · Enter Willow|Continue your town/}).click();await expect(page.locator('#welcome')).toBeHidden({timeout:90000});await expect(page.locator('#town')).toHaveAttribute('data-connected','true');};
test('private world persists, moves, pauses, blocks a second tab and isolates another visitor', async({page,context,browser})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Somewhere to belong.'})).toBeVisible();
  await play(page);
  const start=await page.evaluate(()=>window.__townDebug.player.position);
  await page.locator('#town').focus();await page.keyboard.down('d');await page.waitForTimeout(650);await page.keyboard.up('d');
  await expect.poll(async()=>page.evaluate(()=>window.__townDebug.player.position.x)).toBeGreaterThan(start.x+20);
  await page.getByRole('button',{name:'Return to title screen'}).click();
  await page.waitForTimeout(400);
  const savedPosition=await page.evaluate(async()=>{const {browserAPI}=await import('/browser-runtime.js');return (await browserAPI('/api/state')).actors.find(actor=>actor.id==='player').position;});
  await expect(page.locator('#welcome-save')).toContainText('saved on this device');
  const second=await context.newPage();await second.goto('/');
  await second.getByRole('button',{name:/Continue your town|Play · Enter Willow/}).click();
  await expect(second.locator('#welcome-error')).toContainText('another tab');
  await second.close();
  await page.reload();await expect(page.getByRole('button',{name:'Continue your town →'})).toBeVisible();
  await play(page);
  expect(await page.evaluate(()=>window.__townDebug.player.position.x)).toBeCloseTo(savedPosition.x,0);
  const otherContext=await browser.newContext();const other=await otherContext.newPage();await other.goto('/');await play(other);
  expect(await other.evaluate(()=>window.__townDebug.player.position.x)).toBeCloseTo(start.x,0);
  await otherContext.close();
  expect(errors).toEqual([]);
});
test('local model setup, failures, disconnect, and no key persistence', async({page})=>{
  await page.route('http://127.0.0.1:1234/v1/models', route=>route.fulfill({json:{data:[{id:'local-chat'}]}}));
  await page.route('https://api.openai.com/v1/models', route=>route.fulfill({status:401,json:{error:{message:'unauthorized'}}}));
  await page.goto('/');await page.getByRole('button',{name:'Set up AI'}).click();
  await page.locator('#llm-key-input').fill('fake-key-for-test');await page.getByRole('button',{name:'Connect',exact:true}).click();
  await expect(page.locator('#llm-feedback')).toContainText('key was rejected');
  await page.locator('#llm-provider-input').selectOption('local');
  await expect(page.locator('#local-help')).toBeVisible();
  await expect(page.locator('#llm-model-input')).toHaveValue('');
  await page.getByRole('button',{name:'Connect',exact:true}).click();
  await expect(page.locator('#llm-dialog')).not.toBeVisible();
  await expect(page.locator('#welcome-ai')).toContainText('local-chat');
  await page.getByRole('button',{name:'Set up AI'}).click();
  await expect(page.locator('#llm-key-input')).toHaveValue('');
  await page.getByRole('button',{name:'Disconnect AI'}).click();await expect(page.locator('#welcome-ai')).toContainText('Optional');
  await page.reload();await expect(page.locator('#welcome-ai')).toContainText('Optional');
  expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}))).not.toContain('fake-key');
});
test('mobile title and AI settings stay inside viewport', async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await expect(page.getByRole('button',{name:/Play · Enter Willow/})).toBeInViewport();
  await page.getByRole('button',{name:'Set up AI'}).click();
  await expect(page.locator('#llm-dialog')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({path:'/tmp/willow-mobile-setup.png'});
});
