# Generated by Django 5.1.1 on 2024-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmileAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("smile_score", models.IntegerField()),
                ("is_symmetrical", models.BooleanField()),
                ("has_minimal_gum", models.BooleanField()),
                ("teeth_exposed_correctly", models.BooleanField()),
                ("stain_free", models.BooleanField()),
            ],
        ),
    ]
