/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiManavalanRouteImport } from './routes/api/manavalan'
import { Route as ApiManavalanImageRouteImport } from './routes/api/manavalan-image'
import { Route as ApiManavalanListenRouteImport } from './routes/api/manavalan-listen'
import { Route as ApiManavalanVoiceRouteImport } from './routes/api/manavalan-voice'
import { Route as ApiOllamaStatusRouteImport } from './routes/api/ollama-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManavalanRoute = ApiManavalanRouteImport.update({
  id: '/api/manavalan',
  path: '/api/manavalan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManavalanImageRoute = ApiManavalanImageRouteImport.update({
  id: '/api/manavalan-image',
  path: '/api/manavalan-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManavalanListenRoute = ApiManavalanListenRouteImport.update({
  id: '/api/manavalan-listen',
  path: '/api/manavalan-listen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManavalanVoiceRoute = ApiManavalanVoiceRouteImport.update({
  id: '/api/manavalan-voice',
  path: '/api/manavalan-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOllamaStatusRoute = ApiOllamaStatusRouteImport.update({
  id: '/api/ollama-status',
  path: '/api/ollama-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/manavalan': typeof ApiManavalanRoute
  '/api/manavalan-image': typeof ApiManavalanImageRoute
  '/api/manavalan-listen': typeof ApiManavalanListenRoute
  '/api/manavalan-voice': typeof ApiManavalanVoiceRoute
  '/api/ollama-status': typeof ApiOllamaStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/manavalan': typeof ApiManavalanRoute
  '/api/manavalan-image': typeof ApiManavalanImageRoute
  '/api/manavalan-listen': typeof ApiManavalanListenRoute
  '/api/manavalan-voice': typeof ApiManavalanVoiceRoute
  '/api/ollama-status': typeof ApiOllamaStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/manavalan': typeof ApiManavalanRoute
  '/api/manavalan-image': typeof ApiManavalanImageRoute
  '/api/manavalan-listen': typeof ApiManavalanListenRoute
  '/api/manavalan-voice': typeof ApiManavalanVoiceRoute
  '/api/ollama-status': typeof ApiOllamaStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/manavalan'
    | '/api/manavalan-image'
    | '/api/manavalan-listen'
    | '/api/manavalan-voice'
    | '/api/ollama-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/manavalan'
    | '/api/manavalan-image'
    | '/api/manavalan-listen'
    | '/api/manavalan-voice'
    | '/api/ollama-status'
  id:
    | '__root__'
    | '/'
    | '/api/manavalan'
    | '/api/manavalan-image'
    | '/api/manavalan-listen'
    | '/api/manavalan-voice'
    | '/api/ollama-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiManavalanRoute: typeof ApiManavalanRoute
  ApiManavalanImageRoute: typeof ApiManavalanImageRoute
  ApiManavalanListenRoute: typeof ApiManavalanListenRoute
  ApiManavalanVoiceRoute: typeof ApiManavalanVoiceRoute
  ApiOllamaStatusRoute: typeof ApiOllamaStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manavalan': {
      id: '/api/manavalan'
      path: '/api/manavalan'
      fullPath: '/api/manavalan'
      preLoaderRoute: typeof ApiManavalanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manavalan-image': {
      id: '/api/manavalan-image'
      path: '/api/manavalan-image'
      fullPath: '/api/manavalan-image'
      preLoaderRoute: typeof ApiManavalanImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manavalan-listen': {
      id: '/api/manavalan-listen'
      path: '/api/manavalan-listen'
      fullPath: '/api/manavalan-listen'
      preLoaderRoute: typeof ApiManavalanListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manavalan-voice': {
      id: '/api/manavalan-voice'
      path: '/api/manavalan-voice'
      fullPath: '/api/manavalan-voice'
      preLoaderRoute: typeof ApiManavalanVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ollama-status': {
      id: '/api/ollama-status'
      path: '/api/ollama-status'
      fullPath: '/api/ollama-status'
      preLoaderRoute: typeof ApiOllamaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiManavalanRoute: ApiManavalanRoute,
  ApiManavalanImageRoute: ApiManavalanImageRoute,
  ApiManavalanListenRoute: ApiManavalanListenRoute,
  ApiManavalanVoiceRoute: ApiManavalanVoiceRoute,
  ApiOllamaStatusRoute: ApiOllamaStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
